// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltxmzkbbkeqxujshlwor.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0eG16a2Jia2VxeHVqc2hsd29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTk2ODUsImV4cCI6MjA2NjA3NTY4NX0.bAD2qup_F7FxPB7JO8gF_J4R7qgiXQUxPH4fXpjUpKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Note: Using anon key. Make sure RLS policies allow public read access.